import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../contexts/ThemeContext";
import { LoginProvider } from "../contexts/UserConterx";
import NavBar from "../components/navBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {

  return (

    <ThemeProvider>

      <LoginProvider>

        <html lang="pt-br">

          <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col justify-between h-screen`}>

            <NavBar />
            <div className="flex-1">

              {children}

            </div>

          </body>

        </html>

      </LoginProvider>

    </ThemeProvider>

  )

}
